EmptyTestSites/EmptyNLog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;

namespace EmptyNLog.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            Logger logger = LogManager.GetLogger("serverlogger");
            logger.Warn("Warn Message generated on server");

            return View();
        }

        public ActionResult ConsoleAppender()
        {
            Logger logger = LogManager.GetLogger("serverlogger");
            logger.Warn("Warn Message generated on server, on ConsoleAppender page");

            return View();
        }
    }
}

EmptyTestSites/EmptyNLog/Controllers/Level1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;

namespace EmptyLog4Net.Controllers
{
    public class Level1Controller : Controller
    {
        //
        // GET: /Home/

        public ActionResult Page1()
        {
            Logger logger = LogManager.GetLogger("serverlogger");
            logger.Warn("Warn Message generated on server, Level1/Page1");

            return View();
        }

    }
}

EmptyTestSites/EmptyNLog/Views/Home/ConsoleAppender.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmptyNLog</title>
    @*   @Html.Raw(JSNLog.JavascriptLogging.Configure())   *@
</head>
<body>
    <h1>ConsoleAppender</h1>
    <script>
        // JL("jsLoggerConsoleAndAjax").fatal("fatal log message from jsLoggerConsoleAndAjax");
        // JL("jsLoggerConsole").fatal("fatal log message from jsLoggerConsole");
        // JL("jsLoggerConsole").error("error log message from jsLoggerConsole");
        // JL("jsLoggerConsole").warn("warn log message from jsLoggerConsole");
        // JL("jsLoggerConsole").info("info log message from jsLoggerConsole");
        // JL("jsLoggerConsole").debug("debug log message from jsLoggerConsole");
        // JL("jsLoggerConsole").trace("trace log message from jsLoggerConsole");
        // var ob = { "a": "b", "c": "d", "e": "f" };
        // JL("jsLoggerConsole").debug(ob);
        alert('ConsoleAppender');
    </script>

    <div>
    </div>
</body>
</html>

EmptyTestSites/EmptyNLog/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmptyLog4Net</title>
    @*   @Html.Raw(JSNLog.JavascriptLogging.Configure())   *@
</head>
<body>
    <h1>EmptyNLog</h1>
    <script type="text/ecmascript">
        // JL("jsLogger").fatal("log message");
        alert('nlog');
    </script>

    <div>
    </div>
</body>
</html>

EmptyTestSites/EmptyNLog/Views/Level1/Page1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmptyLog4Net</title>
@*    @Html.Raw(JSNLog.JavascriptLogging.Configure())*@
</head>
<body>
    <h1>EmptyNLog</h1>
    <script type="text/ecmascript">
        // JL("jsLogger").fatal("log message from Level1/Page1");
        alert('nlog from Level1/Page1');
    </script>
        
    <div>
    </div>
</body>
</html>

EmptyTestSites/EmptyNLog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.ActionLink("Home", "Index", "Home")
    |
    @Html.ActionLink("Level1/Page1", "Page1", "Level1")
    |
    @Html.ActionLink("Console Appender", "ConsoleAppender", "Home")


    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>